#!/usr/bin/python3

#
# Copyright (c) 2020 by Philipp Scheer. All Rights Reserved.
#

import sys
import os
import json
import argparse
from jarvis import SetupTools, Config, Colors


parser = argparse.ArgumentParser()
group = parser.add_mutually_exclusive_group(required=True)
group.add_argument("-a", "--add-app",
                   help="download an app from a git repository and install it", type=str)
args = parser.parse_args()


# load jarvis configuration
cnf = Config()
dirs = cnf.get("directories", None)
if dirs is None:
    print("error: jarvis might not be installed yet")
    exit(1)
ROOT_DIR = dirs["root"]
APP_DIR = dirs["root"]
WEB_DIR = dirs["web"]


print(args)
